version: '3.8'
services:
  db:
    image: postgres:15
    container_name: energy-db
    environment:
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432"
